#!/bin/bash

# Instructions extracted from: https://docs.astral.sh/uv/getting-started/installation/#standalone-installer

curl -LsSf https://astral.sh/uv/install.sh | sh

# If your system doesn't have curl, you can use wget:
# wget -qO- https://astral.sh/uv/install.sh | sh

# PyPI
# For convenience, uv is published to PyPI.
# If installing from PyPI, we recommend installing uv into an isolated environment, e.g., with pipx:
#
# pipx install uv
#
# However, pip can also be used:
#
# pip install uv