#!/bin/bash

PACKAGE_NAME=code_1.102.1-1752598717_amd64
PACKAGE_URL=https://vscode.download.prss.microsoft.com/dbazure/download/stable/7adae6a56e34cb64d08899664b814cf620465925/$PACKAGE_NAME.deb

wget $PACKAGE_URL
sudo dpkg --install $PACKAGE_NAME.deb
rm $PACKAGE_NAME.deb
