#!/bin/bash

sudo apt-get remove docker docker-engine docker.io containerd runc

sudo apt-get update

sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

sudo apt-get update -y

sudo apt-get install -y docker-ce docker-ce-cli containerd.io

sudo docker run hello-world


# Post-installation for docker to run without sudo
sudo groupadd docker
sudo usermod -aG docker $USER

docker run hello-world



# Configure Docker to start on boot
# Most current Linux distributions (RHEL, CentOS, Fedora, Ubuntu 16.04 and higher) use systemd to manage which services start when the system boots. Ubuntu 14.10 and below use upstart.

#systemd
sudo systemctl enable docker

#To disable this behavior, use disable instead.
# sudo systemctl disable docker
#If you need to add an HTTP Proxy, set a different directory or partition for the Docker runtime files, or make other customizations, see customize your systemd Docker daemon options.

# upstart
#Docker is automatically configured to start on boot using upstart. To disable this behavior, use the following command:
# echo manual | sudo tee /etc/init/docker.override

#chkconfig
# sudo chkconfig docker on
